goriyak:
  image: gericass/goriyak-golang
  volumes:
    - ".:/go/src/app"
    - "./go:/go"
  environment:
    DSN: docker
  ports:
    - "50051:50051"
  links:
    - mysql:local
    - riak:public

mysql:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: goriyak

riak:
  image: gericass/goriyak-riak

